version: '3.2'

services:
  web:
    image: attendize_web:latest
    ports:
    - "8080:80"
    - "8081:443"
    volumes:
      - .:/usr/share/nginx/html
      - .:/var/www
    depends_on:
      - db
      - maildev
      - redis
      - worker
    env_file:
      - ./.env
  worker:
    image: attendize_worker:latest
    depends_on:
      - db
      - maildev
      - redis
    volumes:
      - .:/usr/share/nginx/html
      - .:/var/www
  db:
    platform: linux/x86_64
    image: mysql
    command: --local-infile=1
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 33066:3306
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
  redis:
    image: redis
